BT/Areas/Cliente/Controllers/FichaTreinoController.cs
using BT.Areas.Cliente.Models;
using BT.Areas.Cliente.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BT.Areas.Cliente.Controllers
{
    public class FichaTreinoController : Controller
    {
        // GET: Management/FichaTreino
        public ActionResult Index()
        {
            int id = Convert.ToInt32(Session["Matricula_UsuarioLogado"]);
            if (id != null)
            {
                FichaTreinoClient CC = new FichaTreinoClient();
                ViewBag.listFichaTreinos = CC.findByMatricula_id(id);
            }
          
            return View();
        }

     
        [HttpGet]
        public ActionResult Create()
        {
            return View("Create");
        }
        [HttpPost]
        public ActionResult Create(FichaTreinoViewModel cvm)
        {
            FichaTreinoClient CC = new FichaTreinoClient();
            CC.Create(cvm.fichaTreino);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            FichaTreinoClient CC = new FichaTreinoClient();
            CC.Delete(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            FichaTreinoClient CC = new FichaTreinoClient();
            FichaTreinoViewModel CVM = new FichaTreinoViewModel();
            CVM.fichaTreino = CC.find(id);
            return View("Edit", CVM);
        }
        [HttpPost]
        public ActionResult Edit(FichaTreinoViewModel CVM)
        {
            FichaTreinoClient CC = new FichaTreinoClient();
            CC.Edit(CVM.fichaTreino);
            return RedirectToAction("Index");
        }
    }
}

BT/Areas/Management/Controllers/FichaTreinoController.cs
using BT.Areas.Management.Models;
using BT.Areas.Management.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BT.Areas.Management.Controllers
{
    public class FichaTreinoController : Controller
    {
        // GET: Management/FichaTreino
        public ActionResult Index()
        {
            FichaTreinoClient CC = new FichaTreinoClient();
            ViewBag.listFichaTreinos = CC.findAll();

            return View();
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View("Create");
        }
        [HttpPost]
        public ActionResult Create(FichaTreinoViewModel cvm)
        {
            FichaTreinoClient CC = new FichaTreinoClient();
            CC.Create(cvm.fichaTreino);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            FichaTreinoClient CC = new FichaTreinoClient();
            CC.Delete(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            FichaTreinoClient CC = new FichaTreinoClient();
            FichaTreinoViewModel CVM = new FichaTreinoViewModel();
            CVM.fichaTreino = CC.find(id);
            return View("Edit", CVM);
        }
        [HttpPost]
        public ActionResult Edit(FichaTreinoViewModel CVM)
        {
            FichaTreinoClient CC = new FichaTreinoClient();
            CC.Edit(CVM.fichaTreino);
            return RedirectToAction("Index");
        }
    }
}

BT/Areas/Professor/Controllers/FichaTreinoController.cs
using BT.Areas.Professor.Models;
using BT.Areas.Professor.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BT.Areas.Professor.Controllers
{
    public class FichaTreinoController : Controller
    {
        // GET: Management/FichaTreino
        public ActionResult Index()
        {
            FichaTreinoClient CC = new FichaTreinoClient();
            ViewBag.listFichaTreinos = CC.findAll();

            return View();
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View("Create");
        }
        [HttpPost]
        public ActionResult Create(FichaTreinoViewModel cvm)
        {
            FichaTreinoClient CC = new FichaTreinoClient();
            CC.Create(cvm.fichaTreino);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            FichaTreinoClient CC = new FichaTreinoClient();
            CC.Delete(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            FichaTreinoClient CC = new FichaTreinoClient();
            FichaTreinoViewModel CVM = new FichaTreinoViewModel();
            CVM.fichaTreino = CC.find(id);
            return View("Edit", CVM);
        }
        [HttpPost]
        public ActionResult Edit(FichaTreinoViewModel CVM)
        {
            FichaTreinoClient CC = new FichaTreinoClient();
            CC.Edit(CVM.fichaTreino);
            return RedirectToAction("Index");
        }
    }
}

BT/Areas/Cliente/Views/FichaTreino/Create.cshtml
@model BT.Areas.Cliente.ViewModel.FichaTreinoViewModel


@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Cliente/Views/Shared/_LayoutCliente.cshtml";

}

<h2>Adicione uma ficha </h2>

<div align="center">
    @using (Html.BeginForm("create", "FichaTreino", FormMethod.Post))
    {
        <table class="table">
            <tr class="btn-default">
                <td>
                    @Html.LabelFor(model => model.fichaTreino.Cliente.clie_nm_nome)
                </td>

                <td>
                    @Html.TextBoxFor(model => model.fichaTreino.Cliente.clie_nm_nome)
                    @*<div class="form-group">
                    @Html.LabelFor(model => model.exercicio.clie_id, "clie_id", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("clie_id", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.exercicio.clie_id, "", new { @class = "text-danger" })
                    </div>
                </div>*@
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.fichaTreino.Cliente.clie_nr_matricula)
                </td>

                <td>
                    @Html.TextBoxFor(model => model.fichaTreino.Cliente.clie_nr_matricula)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.fichaTreino.professor.prof_nm_nome)
                </td>

                <td>
                    @Html.TextBoxFor(model => model.fichaTreino.professor.prof_nm_nome)
                </td>
            </tr>

            <tr>
                <td>
                    @Html.LabelFor(model => model.fichaTreino.exer_nr_ordem)
                </td>

                <td>
                    @Html.TextBoxFor(model => model.fichaTreino.exer_nr_ordem)
                </td>
            </tr>

            <tr>
                <td>
                    @Html.LabelFor(model => model.fichaTreino.exer_nm_nome)
                </td>

                <td>
                    @Html.TextBoxFor(model => model.fichaTreino.exer_nm_nome)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.fichaTreino.exer_nm_repeticao)
                </td>

                <td>
                    @Html.TextBoxFor(model => model.fichaTreino.exer_nm_repeticao)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.fichaTreino.exer_db_carga)
                </td>

                <td>
                    @Html.TextBoxFor(model => model.fichaTreino.exer_db_carga)
                </td>
            </tr>
            <tr>
                <td></td>

                <td>
                    <input type="submit" value="Save" class="btn btn-default" />
                    <a class="btn btn-danger"
                       href="@Url.Action("Index","FichaTreino")">Cancel</a>
                </td>
            </tr>
        </table>
    }
</div>

BT/Areas/Cliente/Views/FichaTreino/Edit.cshtml
@model BT.Areas.Cliente.ViewModel.FichaTreinoViewModel


    @{
        ViewBag.Title = "Edit";
        Layout = "~/Areas/Cliente/Views/Shared/_LayoutCliente.cshtml";

    }

    <h2>Edit </h2>

    <div align="center" width="500px">
        @using (Html.BeginForm("Edit", "FichaTreino", FormMethod.Post))
        {
            <table class="table" width="400px" cellpadding="20">
                <tr class="btn-default">
                    <td>
                        @Html.LabelFor(model => model.fichaTreino.Cliente.clie_nm_nome)
                    </td>

                    <td>
                        @Html.TextBoxFor(model => model.fichaTreino.Cliente.clie_nm_nome)
                        @*<div class="form-group">
                    @Html.LabelFor(model => model.exercicio.clie_id, "clie_id", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("clie_id", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.exercicio.clie_id, "", new { @class = "text-danger" })
                    </div>
                </div>*@
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.fichaTreino.Cliente.clie_nr_matricula)
                    </td>

                    <td>
                        @Html.TextBoxFor(model => model.fichaTreino.Cliente.clie_nr_matricula)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.fichaTreino.professor.prof_nm_nome)
                    </td>

                    <td>
                        @Html.TextBoxFor(model => model.fichaTreino.professor.prof_nm_nome)
                    </td>
                </tr>

                <tr>
                    <td>
                        @Html.LabelFor(model => model.fichaTreino.exer_nr_ordem)
                    </td>

                    <td>
                        @Html.TextBoxFor(model => model.fichaTreino.exer_nr_ordem)
                    </td>
                </tr>

                <tr>
                    <td>
                        @Html.LabelFor(model => model.fichaTreino.exer_nm_nome)
                    </td>

                    <td>
                        @Html.TextBoxFor(model => model.fichaTreino.exer_nm_nome)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.fichaTreino.exer_nm_repeticao)
                    </td>

                    <td>
                        @Html.TextBoxFor(model => model.fichaTreino.exer_nm_repeticao)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.fichaTreino.exer_db_carga)
                    </td>

                    <td>
                        @Html.TextBoxFor(model => model.fichaTreino.exer_db_carga)
                    </td>
                </tr>
              
                <tr>
                    <td></td>

                    <td>
                        <input type="submit" value="Save" class="btn btn-default" />
                        <a class="btn btn-danger"
                           href="@Url.Action("Index","FichaTreino")">Back</a>
                        @Html.HiddenFor(model => model.fichaTreino.Exer_id)
                    </td>
                </tr>
            </table>
        }
    </div>

BT/Areas/Cliente/Views/FichaTreino/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Cliente/Views/Shared/_LayoutCliente.cshtml";
}
<div style="padding-top:20px">
    <h2>Fichas de Treino </h2>

    <div align="center">
        <a href="@Url.Action("Create","FichaTreino")"> Add nova Ficha </a> <br />
        <br />
        <div class="table-responsive">
            <table cellpadding="2"
                   class="table"
                  
                   >
                <tr class="btn-primary">
                    <th> Cliente</th>
                    <th>professor</th>
                    <th> Ordem</th>
                    <th> Exercicio</th>
                    <th>Repeticao</th>
                    <th>Carga</th>
                    <th> Ações</th>
                </tr>
                @foreach (var Cust in ViewBag.listFichaTreinos)
            {
                    <tr class="success">
                        <td>@Cust.Cliente.clie_nm_nome</td>
                        <td>@Cust.professor.prof_nm_nome</td>
                        <td>@Cust.exer_nr_ordem</td>
                        <td>@Cust.exer_nm_nome</td>
                        <td>@Cust.exer_nm_repeticao</td>
                        <td>@Cust.exer_db_carga</td>

                        <td>
                            <a class="btn btn-danger" onclick="return confirm('Do you want to Delete?')"
                               href="@Url.Action("Delete","FichaTreino",new {id= Cust.Exer_id})">Delete</a>
                            ||<a class="btn btn-default" href="@Url.Action("Edit","FichaTreino",new {id= Cust.Exer_id})">Edit</a>
                        </td>
                    </tr>
            }
            </table>

        </div>

    </div>

</div>